export const LANGUAGES = {
  en: '🇬🇧 English',
  fa: '🇮🇷 فارسی',
};

export const LOCALES: Record<string, Record<string, string>> = {
  en: {
    'app_title': 'Proxy Config Tester',
    'dashboard': 'Dashboard',
    'configs': 'Configs',
    'settings': 'Settings',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'add_configs': 'Add Configs',
    'paste_links': 'Paste Links',
    'from_file': 'From File',
    'subscription_url': 'Subscription URL',
    'drop_files_here': 'Drop files here (.json, .txt)',
    'or_click_to_upload': 'or click to upload',
    'process_configs': 'Process Configs',
    'enter_sub_url': 'Enter subscription URL',
    'fetch': 'Fetch',
    'start_testing': 'Start Testing',
    'stop_testing': 'Stop Testing',
    'clear_all': 'Clear All',
    'filter_by_status': 'Filter by Status',
    'all': 'All',
    'active': 'Active',
    'slow': 'Slow',
    'inactive': 'Inactive',
    'untested': 'Untested',
    'testing': 'Testing...',
    'filter_by_protocol': 'Filter by Protocol',
    'filter_by_group': 'Filter by Group',
    'search_by_name_host': 'Search by name/host...',
    'col_name': 'Name',
    'col_protocol': 'Protocol',
    'col_host': 'Host',
    'col_ip': 'IP',
    'col_country': 'Country',
    'col_latency': 'Latency',
    'col_status': 'Status',
    'col_score': 'Score',
    'col_last_tested': 'Last Tested',
    'col_speed': 'Speed',
    'col_group': 'Group',
    'total_configs': 'Total Configs',
    'active_configs': 'Active',
    'inactive_configs': 'Inactive',
    'success_fail': 'Success / Fail',
    'settings_title': 'Application Settings',
    'language': 'Language',
    'test_timeout': 'Test Timeout (ms)',
    'concurrent_tests': 'Concurrent Tests',
    'test_endpoint': 'Test Endpoint',
    'save_settings': 'Save Settings',
    'configs_processed': 'configs processed.',
    'testing_in_progress': 'Testing in progress...',
    'confirm_clear_all': 'Are you sure you want to clear all configs? This action cannot be undone.',
    'yes_clear': 'Yes, Clear All',
    'cancel': 'Cancel',
    'no_configs_to_display': 'No configs to display. Add some to get started!',
    'latency_chart_title': 'Latency Distribution (ms)',
    'status_chart_title': 'Configs by Status',
    'protocol_chart_title': 'Configs by Protocol',
    'welcome_dashboard': 'Welcome to your Dashboard',
    'summary': 'Summary',
    'quick_stats': 'Quick Stats',
    'share_selected': 'Share Selected',
    'delete_selected': 'Delete Selected',
    'set_group': 'Set Group',
    'enter_group_name': 'Enter group name for selected configs:',
    'no_group': 'No Group',
    'copied_to_clipboard': 'Copied!',
    'confirm_delete_selected': 'Are you sure you want to delete the selected configs?',
    'n_selected': '{count} selected',
    'auto_test_settings': 'Auto-testing',
    'auto_test_interval': 'Auto-test Interval',
    'disabled': 'Disabled',
    'minutes': 'minutes',
    'auto_test_only_inactive': 'Test only inactive configs',
    'settings_saved': 'Settings saved successfully!',
    'export_for_hiddify': 'Export for Hiddify',
    'no_active_configs_to_export': 'No active or slow configs were selected to export.',
    'data_management': 'Data Management',
    'export_data': 'Export Data',
    'import_data': 'Import Data',
    'import_confirmation': 'This will overwrite all current settings and configs. Are you sure?',
    'import_success': 'Data imported successfully!',
    'import_error': 'Failed to import data. The file may be invalid.',
    'subscriptions': 'Subscriptions',
    'add_subscription': 'Add Subscription',
    'edit_subscription': 'Edit Subscription',
    'subscription_name': 'Subscription Name',
    'save': 'Save',
    'qr_code': 'QR Code',
    'show_qr_code': 'Show QR Code',
    'fetching_subs': 'Fetching subscriptions...',
    'fetched_n_configs': 'Fetched {count} new configs.',
    'smart_groups': 'Smart Groups',
    'add_smart_group': 'Add Smart Group',
    'edit_smart_group': 'Edit Smart Group',
    'group_name': 'Group Name',
    'group_color': 'Group Color',
    'rules': 'Rules',
    'add_rule': 'Add Rule',
    'field': 'Field',
    'operator': 'Operator',
    'value': 'Value',
    'contains': 'Contains',
    'not_contains': 'Not Contains',
    'equals': 'Equals',
    'not_equals': 'Not Equals',
    'greater_than': 'Greater than',
    'less_than': 'Less than',
    'copy_best': 'Copy Best',
    'best_config_copied': 'Best config copied!',
    'no_active_config_found': 'No active config found to copy.',
    'share_group': 'Share Group',
    'share_link_copied': 'Share link copied to clipboard!',
    'importing_shared_configs': 'Importing shared configs...',
    'imported_n_configs': 'Imported {count} new configs from share link.',
    'all_rules_must_match': 'All rules must match (AND logic)',
  },
  fa: {
    'app_title': 'تست کننده کانفیگ پروکسی',
    'dashboard': 'داشبورد',
    'configs': 'کانفیگ‌ها',
    'settings': 'تنظیمات',
    'dark_mode': 'حالت تاریک',
    'light_mode': 'حالت روشن',
    'add_configs': 'افزودن کانفیگ',
    'paste_links': 'جایگذاری لینک‌ها',
    'from_file': 'از فایل',
    'subscription_url': 'لینک اشتراک',
    'drop_files_here': 'فایل‌ها را اینجا بکشید (.json, .txt)',
    'or_click_to_upload': 'یا برای آپلود کلیک کنید',
    'process_configs': 'پردازش کانفیگ‌ها',
    'fetch': 'واکشی',
    'start_testing': 'شروع تست',
    'stop_testing': 'توقف تست',
    'clear_all': 'پاک کردن همه',
    'filter_by_status': 'فیلتر بر اساس وضعیت',
    'all': 'همه',
    'active': 'فعال',
    'slow': 'کند',
    'inactive': 'غیرفعال',
    'untested': 'تست نشده',
    'testing': 'در حال تست...',
    'filter_by_protocol': 'فیلتر بر اساس پروتکل',
    'filter_by_group': 'فیلتر بر اساس گروه',
    'search_by_name_host': 'جستجو بر اساس نام/هاست...',
    'col_name': 'نام',
    'col_protocol': 'پروتکل',
    'col_host': 'هاست',
    'col_ip': 'IP',
    'col_country': 'کشور',
    'col_latency': 'تأخیر',
    'col_status': 'وضعیت',
    'col_score': 'امتیاز',
    'col_last_tested': 'آخرین تست',
    'col_speed': 'سرعت',
    'col_group': 'گروه',
    'total_configs': 'تعداد کل',
    'active_configs': 'فعال',
    'inactive_configs': 'غیرفعال',
    'success_fail': 'موفق / ناموفق',
    'settings_title': 'تنظیمات برنامه',
    'language': 'زبان',
    'test_timeout': 'وقفه تست (ms)',
    'concurrent_tests': 'تست همزمان',
    'test_endpoint': 'نقطه پایانی تست',
    'save_settings': 'ذخیره تنظیمات',
    'configs_processed': 'کانفیگ پردازش شد.',
    'testing_in_progress': 'در حال انجام تست...',
    'confirm_clear_all': 'آیا از پاک کردن تمام کانفیگ‌ها مطمئن هستید؟ این عمل قابل بازگشت نیست.',
    'yes_clear': 'بله، پاک کن',
    'cancel': 'انصراف',
    'no_configs_to_display': 'هیچ کانفیگی برای نمایش وجود ندارد. برای شروع تعدادی اضافه کنید!',
    'latency_chart_title': 'توزیع تأخیر (ms)',
    'status_chart_title': 'کانفیگ‌ها بر اساس وضعیت',
    'protocol_chart_title': 'کانفیگ‌ها بر اساس پروتکل',
    'welcome_dashboard': 'به داشبورد خود خوش آمدید',
    'summary': 'خلاصه',
    'quick_stats': 'آمار سریع',
    'share_selected': 'اشتراک‌گذاری منتخب',
    'delete_selected': 'حذف منتخب',
    'set_group': 'تنظیم گروه',
    'enter_group_name': 'نام گروه را برای کانفیگ‌های انتخاب شده وارد کنید:',
    'no_group': 'بدون گروه',
    'copied_to_clipboard': 'کپی شد!',
    'confirm_delete_selected': 'آیا از حذف کانفیگ‌های انتخاب شده مطمئن هستید؟',
    'n_selected': '{count} انتخاب شده',
    'auto_test_settings': 'تست خودکار',
    'auto_test_interval': 'فواصل تست خودکار',
    'disabled': 'غیرفعال',
    'minutes': 'دقیقه',
    'auto_test_only_inactive': 'فقط تست کانفیگ‌های غیرفعال',
    'settings_saved': 'تنظیمات با موفقیت ذخیره شد!',
    'export_for_hiddify': 'خروجی برای Hiddify',
    'no_active_configs_to_export': 'هیچ کانفیگ فعال یا کندی برای خروجی گرفتن انتخاب نشده است.',
    'data_management': 'مدیریت داده',
    'export_data': 'خروجی گرفتن از داده‌ها',
    'import_data': 'وارد کردن داده‌ها',
    'import_confirmation': 'این کار تمام تنظیمات و کانفیگ‌های فعلی را بازنویسی می‌کند. آیا مطمئن هستید؟',
    'import_success': 'داده‌ها با موفقیت وارد شد!',
    'import_error': 'وارد کردن داده‌ها ناموفق بود. ممکن است فایل نامعتبر باشد.',
    'subscriptions': 'اشتراک‌ها',
    'add_subscription': 'افزودن اشتراک',
    'edit_subscription': 'ویرایش اشتراک',
    'subscription_name': 'نام اشتراک',
    'save': 'ذخیره',
    'qr_code': 'QR کد',
    'show_qr_code': 'نمایش QR کد',
    'fetching_subs': 'در حال دریافت اشتراک‌ها...',
    'fetched_n_configs': '{count} کانفیگ جدید دریافت شد.',
    'smart_groups': 'گروه‌های هوشمند',
    'add_smart_group': 'افزودن گروه هوشمند',
    'edit_smart_group': 'ویرایش گروه هوشمند',
    'group_name': 'نام گروه',
    'group_color': 'رنگ گروه',
    'rules': 'قوانین',
    'add_rule': 'افزودن قانون',
    'field': 'فیلد',
    'operator': 'عملگر',
    'value': 'مقدار',
    'contains': 'شامل',
    'not_contains': 'شامل نیست',
    'equals': 'برابر است با',
    'not_equals': 'برابر نیست با',
    'greater_than': 'بزرگتر از',
    'less_than': 'کوچکتر از',
    'copy_best': 'کپی بهترین',
    'best_config_copied': 'بهترین کانفیگ کپی شد!',
    'no_active_config_found': 'کانفیگ فعالی برای کپی یافت نشد.',
    'share_group': 'اشتراک‌گذاری گروه',
    'share_link_copied': 'لینک اشتراک‌گذاری کپی شد!',
    'importing_shared_configs': 'در حال وارد کردن کانفیگ‌های اشتراک‌گذاری شده...',
    'imported_n_configs': '{count} کانفیگ جدید از لینک اشتراک‌گذاری وارد شد.',
    'all_rules_must_match': 'همه قوانین باید مطابقت داشته باشند (منطق AND)',
  }
};

export const COUNTRIES: Record<string, { name: string; flag: string }> = {
    US: { name: 'United States', flag: '🇺🇸' },
    DE: { name: 'Germany', flag: '🇩🇪' },
    NL: { name: 'Netherlands', flag: '🇳🇱' },
    FR: { name: 'France', flag: '🇫🇷' },
    GB: { name: 'United Kingdom', flag: '🇬🇧' },
    CA: { name: 'Canada', flag: '🇨🇦' },
    JP: { name: 'Japan', flag: '🇯🇵' },
    SG: { name: 'Singapore', flag: '🇸🇬' },
    UNKNOWN: { name: 'Unknown', flag: '🏳️' }
};
